<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <% request.setCharacterEncoding("UTF-8"); %>

<jsp:include page="header.jsp">
	<jsp:param value="경제" name="title"/>
</jsp:include>	
	<div class="main">
		<h1>경제</h1>	
		<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nisi nulla, aliquet vel tortor sed, bibendum aliquet diam. Fusce vel hendrerit magna, id feugiat lorem. Nam sodales arcu et elementum accumsan. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque aliquet, enim a accumsan varius, sem tellus hendrerit risus, ac tincidunt magna nunc ut felis. Morbi commodo tortor sed quam tristique, et tempus turpis rutrum. Aliquam vitae magna tortor. Ut sollicitudin eget turpis in convallis. Nunc sit amet rutrum justo.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras eros risus, faucibus in ante eu, viverra vestibulum dolor. Quisque porttitor aliquet lorem, et dictum nunc lobortis et. Sed ac magna eu felis ornare blandit vitae maximus nulla. Nam condimentum maximus mi, vitae cursus metus venenatis vitae. Nunc at tempor leo. Mauris ipsum orci, scelerisque sit amet justo eu, pellentesque interdum sapien. Donec mattis consequat sagittis. Mauris a nulla bibendum, placerat nunc nec, commodo metus.

Praesent porta enim id lorem egestas, sed eleifend est mollis. Pellentesque gravida orci eget varius lacinia. Nulla rutrum in leo eu tincidunt. Curabitur posuere vehicula dui, vitae vulputate dolor porta cursus. Nunc nulla odio, auctor nec dui a, sollicitudin tristique ante. Pellentesque sagittis accumsan neque, ut porttitor arcu tempor non. Nullam tincidunt rhoncus blandit. Nullam quis magna ac dolor condimentum laoreet euismod et ex. Mauris varius id erat non condimentum. Suspendisse potenti. Quisque ut mollis ipsum.

Proin tempor, dui vel dapibus facilisis, enim neque suscipit est, at luctus orci magna a dolor. Fusce maximus sit amet nulla venenatis elementum. Mauris ac metus facilisis, faucibus nibh eget, ultrices diam. Morbi finibus justo dictum sapien mollis, ut porttitor urna facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat. Duis sagittis nisi eu diam tempus, eget venenatis tellus facilisis. Nullam sed odio vehicula turpis tincidunt molestie. Sed porttitor efficitur diam nec laoreet. Morbi eleifend felis sit amet pretium euismod. Donec tincidunt accumsan diam quis aliquam. Vivamus ac condimentum nibh. Aliquam convallis elit id commodo elementum. Mauris quis vulputate dolor, porta rutrum tortor. Duis dapibus elementum dolor a luctus.

Aliquam erat volutpat. Nullam bibendum sem eget orci vulputate fringilla. Quisque non ante sit amet tortor efficitur fermentum. Maecenas molestie pretium malesuada. Integer in nunc ante. Nulla rhoncus aliquet nulla. Aenean elementum magna eget orci lacinia fermentum ac vitae odio. Nulla tincidunt lacus lorem, sed eleifend turpis lacinia non. In cursus finibus odio scelerisque gravida. Curabitur et libero sem. Suspendisse sollicitudin ante sed est pharetra accumsan. Duis mollis lorem in fermentum tempus. Cras at mi a diam pretium volutpat. Vivamus pretium lectus eget sapien viverra, nec pellentesque orci dictum.

Duis quis massa at lectus elementum dignissim varius sit amet odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas sit amet egestas felis, gravida gravida eros. Nullam blandit mi sem, et dignissim sapien varius id. Sed sodales accumsan justo sit amet accumsan. Morbi porttitor pretium scelerisque. Aliquam tortor nunc, pulvinar quis odio eget, lobortis ornare purus. Donec pulvinar eleifend vulputate.

Nulla vitae condimentum felis. Aliquam interdum justo sed orci condimentum, at pellentesque nisl pellentesque. Vivamus et velit metus. Nullam porta facilisis iaculis. Quisque efficitur aliquam viverra. Maecenas consectetur augue vel sodales euismod. Pellentesque ullamcorper lorem nunc, sed eleifend orci pulvinar et. Nulla malesuada sit amet lectus in consequat. Vivamus aliquam scelerisque sodales. Nunc vitae sodales odio. Nam lorem eros, facilisis sed ante tincidunt, tempor rhoncus lectus. Curabitur lacus elit, feugiat in luctus ut, tincidunt sit amet tortor. Etiam quis semper urna, et mattis urna.

Aenean eget venenatis felis, ac suscipit tortor. Donec sed sollicitudin nibh. Ut aliquet ultricies venenatis. Morbi vitae nisl luctus, suscipit purus id, lobortis nisi. Praesent venenatis ut orci malesuada volutpat. Vestibulum eleifend convallis bibendum. Sed quis quam ante. Sed iaculis nulla enim, id dictum libero dignissim vel. Fusce hendrerit molestie rutrum. Phasellus id lacus convallis enim facilisis blandit vitae a velit.

Etiam sit amet ullamcorper erat. Aliquam mattis eleifend ante nec sollicitudin. Praesent nec sapien a neque molestie fringilla at ut lacus. Suspendisse ac iaculis ex. Curabitur vel egestas arcu. Curabitur faucibus tortor at tempor viverra. Etiam scelerisque, nisl nec lacinia vehicula, lacus risus mattis leo, ac suscipit mi dolor sit amet augue. Sed faucibus purus metus, vel rutrum ex ullamcorper eu. Sed a urna metus. Vestibulum tempus lobortis enim in eleifend.

Morbi congue ultricies dignissim. Aenean posuere mi eget nisi porttitor, consectetur mattis risus pulvinar. Quisque a dui in velit bibendum suscipit id eget lorem. Maecenas efficitur eros id nulla interdum, ut tincidunt urna vestibulum. Vivamus a orci facilisis, viverra tortor eget, aliquet nisl. Nam auctor pellentesque nisl, id pharetra elit tincidunt id. Praesent eget suscipit velit, non elementum lectus. Sed nec venenatis odio, sed accumsan mi. Nunc purus nulla, ultricies non enim id, iaculis congue urna. Vivamus commodo in turpis nec pharetra. Mauris a elit a justo hendrerit pellentesque. Suspendisse tincidunt porta vulputate. Morbi quis viverra erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</div>
	</div>

	<%@ include file="footer.jsp" %>